name             'main'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures main'
long_description 'Installs/Configures main'
version          '0.1.0'

depends 'yum'
# depends 'wget'
depends 'git'
depends 'curl'
depends 'screen'
depends 'sshd'
depends 'ntp'
depends 'openssl'
depends 'iptables'
depends 'firewalld'
depends 'chef-client'
depends 'nginx'
